# Generated by Django 4.1 on 2022-08-26 18:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_bio_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('658dae49-96ee-466e-8a56-ac2be4f815e2'), primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
