# Generated by Django 4.1 on 2022-09-02 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followers_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f136d695-5938-484f-9448-2d4b49c0708b'), primary_key=True, serialize=False),
        ),
    ]
